excluded:
  - Pods
disabled_rules:
  - type_body_length
  - todo
opt_in_rules:
  - implicit_return
  - vertical_parameter_alignment_on_call

line_length:
  warning: 140
  ignores_comments: true

file_length:
  warning: 200
  error: 400

type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50

identifier_name:
  max_length: 45
  validates_start_with_lowercase: true
  allowed_symbols:
    - _
  excluded:
    - id
    - vc
    - x
    - y
    - ok
    - on